POST http://localhost:3000/api/alerts
Content-Type: application/json

{
  "title": "test post",
  "service_id": "abc",
  "start_date": "20211108",
  "close_date": "20220101",
  "label": "test",
  "url": "localhost:3000",
  "information_id": null,
  "information_html": null
}
###

GET http://localhost:3000/api/alerts/1
Content-Type: application/json

###



POST http://localhost:3000/api/read?user_id=1&alert_id=1
Content-Type: application/json

###